// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: gettingStartedAgain

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_Spinner3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_timer1 = NULL;
lv_obj_t * ui_timer2 = NULL;
lv_obj_t * ui_timer3 = NULL;
lv_obj_t * ui_Spinner4 = NULL;
lv_obj_t * ui_Spinner5 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 56);
    lv_obj_set_y(ui_Switch3, -82);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch3, LV_STATE_CHECKED);       /// States

    ui_Switch2 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 56);
    lv_obj_set_y(ui_Switch2, -112);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch2, LV_STATE_CHECKED);       /// States

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 56);
    lv_obj_set_y(ui_Switch1, -141);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States

    ui_Switch4 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 53);
    lv_obj_set_y(ui_Switch4, 135);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    ui_Switch5 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, -21);
    lv_obj_set_y(ui_Switch5, -140);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);

    ui_Spinner3 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 46);
    lv_obj_set_height(ui_Spinner3, 43);
    lv_obj_set_x(ui_Spinner3, -44);
    lv_obj_set_y(ui_Spinner3, -84);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xCAD626), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x020212), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 15);
    lv_obj_set_y(ui_Label3, -141);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 17);
    lv_obj_set_y(ui_Label4, -109);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 17);
    lv_obj_set_y(ui_Label5, -79);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "3");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -65);
    lv_obj_set_y(ui_Label6, -140);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "but");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 16);
    lv_obj_set_y(ui_Label7, 134);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "4");

    ui_timer1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer1, 16);
    lv_obj_set_y(ui_timer1, 109);
    lv_label_set_text(ui_timer1, "timer1");

    ui_timer2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer2, 17);
    lv_obj_set_y(ui_timer2, 179);
    lv_label_set_text(ui_timer2, "timer2");

    ui_timer3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timer3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer3, 17);
    lv_obj_set_y(ui_timer3, 256);
    lv_label_set_text(ui_timer3, "timer3");

    ui_Spinner4 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 46);
    lv_obj_set_height(ui_Spinner4, 80);
    lv_obj_set_x(ui_Spinner4, -47);
    lv_obj_set_y(ui_Spinner4, 10);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_width(ui_Spinner4, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Spinner5 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner5, 48);
    lv_obj_set_height(ui_Spinner5, 80);
    lv_obj_set_x(ui_Spinner5, -48);
    lv_obj_set_y(ui_Spinner5, 79);
    lv_obj_set_align(ui_Spinner5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner5, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner5, lv_color_hex(0x40FF5E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner5, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Switch3 = NULL;
    ui_Switch2 = NULL;
    ui_Switch1 = NULL;
    ui_Switch4 = NULL;
    ui_Switch5 = NULL;
    ui_Spinner3 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_timer1 = NULL;
    ui_timer2 = NULL;
    ui_timer3 = NULL;
    ui_Spinner4 = NULL;
    ui_Spinner5 = NULL;

}
