// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: gettingStartedAgain

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_value = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Switch6 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 80);
    lv_obj_set_height(ui_Spinner2, 43);
    lv_obj_set_x(ui_Spinner2, -112);
    lv_obj_set_y(ui_Spinner2, -59);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4182DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFD330D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_value = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_value, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 56);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Value");

    ui_Switch6 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, -124);
    lv_obj_set_y(ui_Switch6, 63);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -122);
    lv_obj_set_y(ui_Label8, 40);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "4");

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Spinner2 = NULL;
    ui_Arc1 = NULL;
    ui_value = NULL;
    ui_Label2 = NULL;
    ui_Switch6 = NULL;
    ui_Label8 = NULL;

}
