// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: gettingStartedAgain

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_timer1;
extern lv_obj_t * ui_timer2;
extern lv_obj_t * ui_timer3;
extern lv_obj_t * ui_Spinner4;
extern lv_obj_t * ui_Spinner5;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

